[build-system]
requires = ["flit", "pygame"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "pyparadigm"
author = "Felix G. Knorr"
author-email = "felix.knorr@gmx.de"
home-page = "http://None.com"
classifiers = ["License :: OSI Approved :: MIT License"]

