[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "pyparadigm"
author = "Felix Knorr"
author-email = "knorr.felix@tu-dresden.de"
home-page = "http://None.com"
classifiers = ["License :: OSI Approved :: MIT License"]

