#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pyparadigm']

package_data = \
{'': ['*']}

install_requires = \
['pygame>=1.9.3']

setup(name='pyparadigm',
      version='1.0.3',
      description='A package to build psychological Paradigms. Based on PyGame ',
      author='Felix G. Knorr',
      author_email='knorr.felix@gmx.de',
      url='https://github.com/KnorrFG/pyparadigm',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.5',
     )
